.PHONY: clean All

All:
	@echo "----------Building project:[ 37-Overview-of-the-Structure-of-a-Cpp-Program - Debug ]----------"
	@cd "37-Overview-of-the-Structure-of-a-Cpp-Program" && "$(MAKE)" -f  "37-Overview-of-the-Structure-of-a-Cpp-Program.mk"
clean:
	@echo "----------Cleaning project:[ 37-Overview-of-the-Structure-of-a-Cpp-Program - Debug ]----------"
	@cd "37-Overview-of-the-Structure-of-a-Cpp-Program" && "$(MAKE)" -f  "37-Overview-of-the-Structure-of-a-Cpp-Program.mk" clean
