.PHONY: clean All

All:
	@echo "----------Building project:[ 41-Namespaces - Debug ]----------"
	@cd "41-Namespaces" && "$(MAKE)" -f  "41-Namespaces.mk"
clean:
	@echo "----------Cleaning project:[ 41-Namespaces - Debug ]----------"
	@cd "41-Namespaces" && "$(MAKE)" -f  "41-Namespaces.mk" clean
