.PHONY: clean All

All:
	@echo "----------Building project:[ 39-Comments - Debug ]----------"
	@cd "39-Comments" && "$(MAKE)" -f  "39-Comments.mk"
clean:
	@echo "----------Cleaning project:[ 39-Comments - Debug ]----------"
	@cd "39-Comments" && "$(MAKE)" -f  "39-Comments.mk" clean
